version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
